BEGIN TRANSACTION;
ALTER TABLE devices ADD COLUMN battery_level NUMERIC NOT NULL DEFAULT 100;
ALTER TABLE devices ADD COLUMN battery_status TEXT;
ALTER TABLE devices ADD COLUMN updated_at TEXT;
COMMIT;
